import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="h-screen w-screen flex flex-col items-center">
      <Head>
        <title>Vote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-4">
        <p className="text-4xl text-center">Which do you like better?</p>
      </div>
    </div>
  );
};

export default Home;
