import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="h-screen w-screen flex flex-col justify-between items-center">
      <Head>
        <title>Vote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-4">
        <p className="text-4xl text-center">which do you like better?</p>
      </div>
      <div className="p-8 flex flex-col space-x-8 space-y-3 items-baseline md:flex-row">
        <EmojiTemplate emoji="🦊" />
        <div className="text-3xl">
          <p>or</p>
        </div>
        <EmojiTemplate emoji="🐻‍❄️" />
      </div>
      <div className="pb-2 text-2xl"> results </div>
    </div>
  );
}

type EmojiTemplateProps = {
  emoji: string;
};

const EmojiTemplate = ({ emoji }: EmojiTemplateProps) => {
  return (
    <div className="flex flex-col space-y-8 items-center">
      <p className="text-8xl">{emoji}</p>
      <button className="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded">
        this one
      </button>
    </div>
  );
};
